import {
  AlertTriangle,
  ArrowRight,
  ArrowUpDown,
  Bell,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  Copy,
  DoorClosed,
  DoorOpen,
  Download,
  Edit,
  ExternalLink,
  File,
  FileAudio,
  Filter,
  Folder,
  Globe,
  History,
  Inbox,
  Info,
  Link as LinkIcon,
  Loader,
  Lock,
  Mic,
  Moon,
  MoreHorizontal,
  Plus,
  Radio,
  RefreshCw,
  RotateCcw,
  Search,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Sun,
  Tag,
  Trash2,
  Undo,
  Upload,
  User,
  Users,
  Waves,
  X,
} from 'lucide-react'

export {
  AlertTriangle,
  ArrowRight,
  Bell,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  Copy,
  Download,
  Edit,
  ExternalLink,
  File,
  FileAudio,
  Filter,
  Folder,
  Globe,
  History,
  Inbox,
  Info,
  Loader,
  Lock,
  Mic,
  Moon,
  Plus,
  Radio,
  RefreshCw,
  RotateCcw,
  Search,
  Settings,
  Shield,
  Sparkles,
  Sun,
  Tag,
  Undo,
  Upload,
  User,
  Users,
  Waves,
  X,
}
export { DoorClosed as Door }
export { DoorOpen }
export { Trash2 as Trash }
export { MoreHorizontal as More }
export { Share2 as Share }
export { ArrowUpDown as Swap }
export { LinkIcon as Link }
export { X as Close }

const make = (Icon: typeof Mic) => (size = 16) => <Icon size={size} strokeWidth={1.75} />

export const I = {
  Inbox: make(Inbox),
  Mic: make(Mic),
  Upload: make(Upload),
  Radio: make(Radio),
  Door: make(DoorClosed),
  Folder: make(Folder),
  Trash: make(Trash2),
  Tag: make(Tag),
  Users: make(Users),
  Search: make(Search),
  Plus: make(Plus),
  Bell: make(Bell),
  Settings: make(Settings),
  Close: make(X),
  Download: make(Download),
  Share: make(Share2),
  More: make(MoreHorizontal),
  Globe: make(Globe),
  Clock: make(Clock),
  CheckCircle: make(CheckCircle2),
  AlertTriangle: make(AlertTriangle),
  Loader: make(Loader),
  ChevronDown: make(ChevronDown),
  ChevronLeft: make(ChevronLeft),
  ChevronRight: make(ChevronRight),
  Sparkle: make(Sparkles),
  Waves: make(Waves),
  Filter: make(Filter),
  Undo: make(Undo),
  Edit: make(Edit),
  Refresh: make(RefreshCw),
  ExternalLink: make(ExternalLink),
  RotateCcw: make(RotateCcw),
  X: make(X),
  Info: make(Info),
  Check: make(Check),
  Moon: make(Moon),
  Sun: make(Sun),
  Lock: make(Lock),
  Shield: make(Shield),
  Swap: make(ArrowUpDown),
  ArrowRight: make(ArrowRight),
  History: make(History),
  DoorOpen: make(DoorOpen),
  FileAudio: make(FileAudio),
  File: make(File),
  Calendar: make(Calendar),
  Link: make(LinkIcon),
  Cloud: make(Cloud),
  User: make(User),
  Copy: make(Copy),
}
